### ISSUE TITLE
Web-app prototype

### ISSUE THREAD

**Issue by Artq99** [Artq99/artushima#11]
In order to extend the abilities of the application, a new frontend should be introduced - a web-app created in Angular.

This task is about providing a prototype of such application and adjusting the existing code to the requirements.

**To do:**

- [x] The main flask-app should provide only one view - the index of the Angular app
- [x] All other views should be converted into REST API endpoints
- [x] The usage of the flask.session should be removed - required authentication should be token-based
- [x] Working login, logout and dashboard functionalities
- [x] Cleanup after the implementation

The issue will be implemented on the separate branch `dev_webapp_prototype`.

When all the to-dos in this issue are implemented, the branch will be able to be merged into the main development branch.

**Comment by Artq99** [comment]
The prototype for the web-application has been implemented. The branch `dev_webapp_prototype` has been merged into `dev`.
