### ISSUE TITLE
Migrate the POC

### ISSUE THREAD

**Issue by Artq99** [Artq99/artushima#5]
The functionalities provided by the POC should be implemented in the app.

The functionalities to migrate:

- [x] Creation of the superuser #10
- [x] User authentication #6 
- [x] Roles #7 
- [x] Managing users by users with administrator privileges #8 
- [x] Displaying a list of campaigns run by the currently logged in game master #9

**Comment by Artq99** [comment]
Resolved. All the functionalities from the PoC has been implemented.
